# This file was automatically generated by passthru.fetch-deps.
# Please don't edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.31.0";
    hash = "sha256-ed3FVERXwVHAXdy+iDEppbpuDUbVqErGczNVw1BEWzE=";
  })
]
