<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT! (protoc-gen-twirp_php 0.13.0)
# source: test-proto.proto

declare(strict_types=1);

namespace Test;

/**
 * Simple greeting service example
 *
 * Generated from protobuf service <code>test.HelloService</code>
 */
interface HelloService
{
    /**
     * Say hello
     *
     * Generated from protobuf method <code>test.HelloService/Hello</code>
     *
     * @throws \Twirp\Error
     */
    public function Hello(array $ctx, \Test\HelloRequest $req): \Test\HelloResponse;
}
