<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test-proto.proto

namespace GPBMetadata;

class TestProto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA3\x01\x0A\x10test-proto.proto\x12\x04test\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"!\x0A\x0DHelloResponse\x12\x10\x0A\x08greeting\x18\x01 \x01(\x092@\x0A\x0CHelloService\x120\x0A\x05Hello\x12\x12.test.HelloRequest\x1A\x13.test.HelloResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

