# This file was automatically generated by passthru.fetch-deps.
# Please don't edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Google.Protobuf"; version = "3.31.0"; hash = "sha256-1RJaYpv7+4wREj3ixYg5BEcj1476CpnKb6Dh8xDDvqo="; })
  (fetchNuGet { pname = "Grpc.AspNetCore"; version = "2.72.0"; hash = "sha256-NdQLcJp5sE2wvL1i9qdGnhYQfpDO0idRdH9l8xVhAPw="; })
  (fetchNuGet { pname = "Grpc.AspNetCore.Server"; version = "2.72.0"; hash = "sha256-gPp2oI2u05K7StbnyQW8FgJSkPxDZ7aDq7xOlBfgKLo="; })
  (fetchNuGet { pname = "Grpc.AspNetCore.Server.ClientFactory"; version = "2.72.0"; hash = "sha256-Mf5t3SsVGAi5SnPJUxb+T5T6EZuCOx0uPdH4LKqBcAI="; })
  (fetchNuGet { pname = "Grpc.Core.Api"; version = "2.72.0"; hash = "sha256-BixqsU2XkZMssVVSCrQrJNq/wjMksFKpuLkYYRZL2UE="; })
  (fetchNuGet { pname = "Grpc.Net.Client"; version = "2.72.0"; hash = "sha256-4qBjLgvhPPaYmjEW8XQuQpO6lBrTWoc8mm8LxwCXqJU="; })
  (fetchNuGet { pname = "Grpc.Net.ClientFactory"; version = "2.72.0"; hash = "sha256-PJmsJvO8v08MPawBwjuXYxGTEWOHZhfVQk/LJkQZDcQ="; })
  (fetchNuGet { pname = "Grpc.Net.Common"; version = "2.72.0"; hash = "sha256-SiDI8F1A1Bfw9qzaDYZCWNrHHJNNEaowqk0X0HnoFKI="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Configuration"; version = "8.0.0"; hash = "sha256-xPqHVW4JN3kfDRUCRlkqLqQ5TLU5RX5pBdchtyHRyVU="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Configuration.Abstractions"; version = "8.0.0"; hash = "sha256-6qM1g6tqPCIrL8OFqhBMDi7FqhWOi8Lao20xMWNSRtc="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Configuration.Binder"; version = "8.0.0"; hash = "sha256-mzDJf5GhehO2+TtfI5zt+Mbs41pJ7iNPqLFjQbqgDvg="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyInjection"; version = "8.0.0"; hash = "sha256-ydg5XZD0WYa7aQCHnGMx1fpXJsBA1wNKcsKNJgPGp54="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyInjection.Abstractions"; version = "8.0.0"; hash = "sha256-D5gCr+B2Dp8+5k5Dg1LR1coKIFpvsNdVZ2EqMCwM0sU="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Http"; version = "8.0.0"; hash = "sha256-pYhsB5S3PcjKMIBUbu3+9qCao1GQHGLqE7lqLf8IFWM="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Logging"; version = "8.0.0"; hash = "sha256-MJ0T3xNsqM+Av3qGn8XeGGlHhTj1Em7m2CqEvRnggqc="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Logging.Abstractions"; version = "8.0.0"; hash = "sha256-M5g1PXjqC8ILqCqhRlXH6eYMPgwT6spBiP5BV6Ndr6U="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Options"; version = "8.0.0"; hash = "sha256-VTn9FqfEEFV7e7MwX23jZOEhLqfFHCvFcV9lEcXPQOk="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Options.ConfigurationExtensions"; version = "8.0.0"; hash = "sha256-C1JAH7OPIYnZt7vmQKYpe2gZd8oLA5X6Hah5nJPGmC8="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Primitives"; version = "8.0.0"; hash = "sha256-oGrLQAa7ZJD9yuAqBN7i8XqpkYkek8bMWYozeSGXWF8="; })
]