name: dart_example
description: A comprehensive Dart example for bufrnix protobuf code generation
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  protobuf: ^3.1.0
  grpc: ^4.0.1
  fixnum: ^1.1.0
dev_dependencies:
  test: ^1.25.2
  lints: ^4.0.0
dependency_overrides:
  # Pin to specific versions for consistency
  protobuf: 3.1.0
