// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: payments/v1/payment.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethodType enum
type PaymentMethodType int32

const (
	PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED    PaymentMethodType = 0
	PaymentMethodType_PAYMENT_METHOD_TYPE_CARD           PaymentMethodType = 1
	PaymentMethodType_PAYMENT_METHOD_TYPE_BANK_TRANSFER  PaymentMethodType = 2
	PaymentMethodType_PAYMENT_METHOD_TYPE_DIGITAL_WALLET PaymentMethodType = 3
	PaymentMethodType_PAYMENT_METHOD_TYPE_CRYPTOCURRENCY PaymentMethodType = 4
)

// Enum value maps for PaymentMethodType.
var (
	PaymentMethodType_name = map[int32]string{
		0: "PAYMENT_METHOD_TYPE_UNSPECIFIED",
		1: "PAYMENT_METHOD_TYPE_CARD",
		2: "PAYMENT_METHOD_TYPE_BANK_TRANSFER",
		3: "PAYMENT_METHOD_TYPE_DIGITAL_WALLET",
		4: "PAYMENT_METHOD_TYPE_CRYPTOCURRENCY",
	}
	PaymentMethodType_value = map[string]int32{
		"PAYMENT_METHOD_TYPE_UNSPECIFIED":    0,
		"PAYMENT_METHOD_TYPE_CARD":           1,
		"PAYMENT_METHOD_TYPE_BANK_TRANSFER":  2,
		"PAYMENT_METHOD_TYPE_DIGITAL_WALLET": 3,
		"PAYMENT_METHOD_TYPE_CRYPTOCURRENCY": 4,
	}
)

func (x PaymentMethodType) Enum() *PaymentMethodType {
	p := new(PaymentMethodType)
	*p = x
	return p
}

func (x PaymentMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethodType) Type() protoreflect.EnumType {
	return &file_payments_v1_payment_proto_enumTypes[0]
}

func (x PaymentMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodType.Descriptor instead.
func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{0}
}

// PaymentStatus represents the current status of a payment
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED        PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING            PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_AUTHORIZED         PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_CAPTURED           PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_SETTLED            PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_FAILED             PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_CANCELLED          PaymentStatus = 6
	PaymentStatus_PAYMENT_STATUS_REFUNDED           PaymentStatus = 7
	PaymentStatus_PAYMENT_STATUS_PARTIALLY_REFUNDED PaymentStatus = 8
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_AUTHORIZED",
		3: "PAYMENT_STATUS_CAPTURED",
		4: "PAYMENT_STATUS_SETTLED",
		5: "PAYMENT_STATUS_FAILED",
		6: "PAYMENT_STATUS_CANCELLED",
		7: "PAYMENT_STATUS_REFUNDED",
		8: "PAYMENT_STATUS_PARTIALLY_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED":        0,
		"PAYMENT_STATUS_PENDING":            1,
		"PAYMENT_STATUS_AUTHORIZED":         2,
		"PAYMENT_STATUS_CAPTURED":           3,
		"PAYMENT_STATUS_SETTLED":            4,
		"PAYMENT_STATUS_FAILED":             5,
		"PAYMENT_STATUS_CANCELLED":          6,
		"PAYMENT_STATUS_REFUNDED":           7,
		"PAYMENT_STATUS_PARTIALLY_REFUNDED": 8,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_v1_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payments_v1_payment_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{1}
}

// Payment represents a payment transaction
type Payment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the payment
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Order ID this payment is for
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID who made the payment
	CustomerId string `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Payment amount in cents
	AmountCents int64 `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// Currency code (e.g., USD, EUR)
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Payment method used
	Method *PaymentMethod `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	// Payment status
	Status PaymentStatus `protobuf:"varint,7,opt,name=status,proto3,enum=payments.v1.PaymentStatus" json:"status,omitempty"`
	// Payment processor transaction ID
	ProcessorTransactionId string `protobuf:"bytes,8,opt,name=processor_transaction_id,json=processorTransactionId,proto3" json:"processor_transaction_id,omitempty"`
	// Payment creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Payment processing timestamp
	ProcessedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payments_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Payment) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetMethod() *PaymentMethod {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetProcessorTransactionId() string {
	if x != nil {
		return x.ProcessorTransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PaymentMethod represents the method used for payment
type PaymentMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of payment method
	Type PaymentMethodType `protobuf:"varint,1,opt,name=type,proto3,enum=payments.v1.PaymentMethodType" json:"type,omitempty"`
	// Card details (if type is CARD)
	Card *CardDetails `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	// Bank account details (if type is BANK_TRANSFER)
	BankAccount *BankAccountDetails `protobuf:"bytes,3,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	// Digital wallet details (if type is DIGITAL_WALLET)
	DigitalWallet *DigitalWalletDetails `protobuf:"bytes,4,opt,name=digital_wallet,json=digitalWallet,proto3" json:"digital_wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payments_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMethod) GetType() PaymentMethodType {
	if x != nil {
		return x.Type
	}
	return PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED
}

func (x *PaymentMethod) GetCard() *CardDetails {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PaymentMethod) GetBankAccount() *BankAccountDetails {
	if x != nil {
		return x.BankAccount
	}
	return nil
}

func (x *PaymentMethod) GetDigitalWallet() *DigitalWalletDetails {
	if x != nil {
		return x.DigitalWallet
	}
	return nil
}

// CardDetails represents credit/debit card information
type CardDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last 4 digits of the card
	LastFour string `protobuf:"bytes,1,opt,name=last_four,json=lastFour,proto3" json:"last_four,omitempty"`
	// Card brand (e.g., VISA, MASTERCARD)
	Brand string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	// Expiration month
	ExpMonth int32 `protobuf:"varint,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	// Expiration year
	ExpYear int32 `protobuf:"varint,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	// Cardholder name
	CardholderName string `protobuf:"bytes,5,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CardDetails) Reset() {
	*x = CardDetails{}
	mi := &file_payments_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDetails) ProtoMessage() {}

func (x *CardDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardDetails.ProtoReflect.Descriptor instead.
func (*CardDetails) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CardDetails) GetLastFour() string {
	if x != nil {
		return x.LastFour
	}
	return ""
}

func (x *CardDetails) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CardDetails) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *CardDetails) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *CardDetails) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

// BankAccountDetails represents bank account information
type BankAccountDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bank name
	BankName string `protobuf:"bytes,1,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	// Account holder name
	AccountHolderName string `protobuf:"bytes,2,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	// Last 4 digits of account number
	AccountLastFour string `protobuf:"bytes,3,opt,name=account_last_four,json=accountLastFour,proto3" json:"account_last_four,omitempty"`
	// Routing number (masked)
	RoutingNumberMasked string `protobuf:"bytes,4,opt,name=routing_number_masked,json=routingNumberMasked,proto3" json:"routing_number_masked,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BankAccountDetails) Reset() {
	*x = BankAccountDetails{}
	mi := &file_payments_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountDetails) ProtoMessage() {}

func (x *BankAccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountDetails.ProtoReflect.Descriptor instead.
func (*BankAccountDetails) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *BankAccountDetails) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankAccountDetails) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

func (x *BankAccountDetails) GetAccountLastFour() string {
	if x != nil {
		return x.AccountLastFour
	}
	return ""
}

func (x *BankAccountDetails) GetRoutingNumberMasked() string {
	if x != nil {
		return x.RoutingNumberMasked
	}
	return ""
}

// DigitalWalletDetails represents digital wallet information
type DigitalWalletDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wallet provider (e.g., PAYPAL, APPLE_PAY, GOOGLE_PAY)
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Wallet account identifier (masked)
	AccountIdMasked string `protobuf:"bytes,2,opt,name=account_id_masked,json=accountIdMasked,proto3" json:"account_id_masked,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DigitalWalletDetails) Reset() {
	*x = DigitalWalletDetails{}
	mi := &file_payments_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalWalletDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalWalletDetails) ProtoMessage() {}

func (x *DigitalWalletDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalWalletDetails.ProtoReflect.Descriptor instead.
func (*DigitalWalletDetails) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *DigitalWalletDetails) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DigitalWalletDetails) GetAccountIdMasked() string {
	if x != nil {
		return x.AccountIdMasked
	}
	return ""
}

// Request message for ProcessPayment
type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payments_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *ProcessPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *ProcessPaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response message for ProcessPayment
type ProcessPaymentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Payment        *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	RequiresAction bool                   `protobuf:"varint,2,opt,name=requires_action,json=requiresAction,proto3" json:"requires_action,omitempty"`
	ActionUrl      string                 `protobuf:"bytes,3,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_payments_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *ProcessPaymentResponse) GetRequiresAction() bool {
	if x != nil {
		return x.RequiresAction
	}
	return false
}

func (x *ProcessPaymentResponse) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

// Request message for GetPayment
type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payments_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for GetPayment
type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_payments_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Request message for CapturePayment
type CapturePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"` // Optional: for partial capture
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePaymentRequest) Reset() {
	*x = CapturePaymentRequest{}
	mi := &file_payments_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePaymentRequest) ProtoMessage() {}

func (x *CapturePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePaymentRequest.ProtoReflect.Descriptor instead.
func (*CapturePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *CapturePaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapturePaymentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

// Response message for CapturePayment
type CapturePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePaymentResponse) Reset() {
	*x = CapturePaymentResponse{}
	mi := &file_payments_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePaymentResponse) ProtoMessage() {}

func (x *CapturePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePaymentResponse.ProtoReflect.Descriptor instead.
func (*CapturePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *CapturePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Request message for RefundPayment
type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"` // Optional: for partial refund
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payments_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *RefundPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefundPaymentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Response message for RefundPayment
type RefundPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	RefundId      string                 `protobuf:"bytes,2,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentResponse) Reset() {
	*x = RefundPaymentResponse{}
	mi := &file_payments_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentResponse) ProtoMessage() {}

func (x *RefundPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentResponse.ProtoReflect.Descriptor instead.
func (*RefundPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *RefundPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *RefundPaymentResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

// Request message for ListPayments
type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StatusFilter  PaymentStatus          `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=payments.v1.PaymentStatus" json:"status_filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_payments_v1_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{13}
}

func (x *ListPaymentsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListPaymentsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ListPaymentsRequest) GetStatusFilter() PaymentStatus {
	if x != nil {
		return x.StatusFilter
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *ListPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for ListPayments
type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_payments_v1_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{14}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListPaymentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request message for GetPaymentStatus
type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_payments_v1_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{15}
}

func (x *GetPaymentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for GetPaymentStatus
type GetPaymentStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payments.v1.PaymentStatus" json:"status,omitempty"`
	StatusUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_payments_v1_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payment_proto_rawDescGZIP(), []int{16}
}

func (x *GetPaymentStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPaymentStatusResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *GetPaymentStatusResponse) GetStatusUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return nil
}

var File_payments_v1_payment_proto protoreflect.FileDescriptor

const file_payments_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x19payments/v1/payment.proto\x12\vpayments.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x122\n" +
	"\x06method\x18\x06 \x01(\v2\x1a.payments.v1.PaymentMethodR\x06method\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x1a.payments.v1.PaymentStatusR\x06status\x128\n" +
	"\x18processor_transaction_id\x18\b \x01(\tR\x16processorTransactionId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fprocessed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12>\n" +
	"\bmetadata\x18\v \x03(\v2\".payments.v1.Payment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\rPaymentMethod\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.payments.v1.PaymentMethodTypeR\x04type\x12,\n" +
	"\x04card\x18\x02 \x01(\v2\x18.payments.v1.CardDetailsR\x04card\x12B\n" +
	"\fbank_account\x18\x03 \x01(\v2\x1f.payments.v1.BankAccountDetailsR\vbankAccount\x12H\n" +
	"\x0edigital_wallet\x18\x04 \x01(\v2!.payments.v1.DigitalWalletDetailsR\rdigitalWallet\"\xa1\x01\n" +
	"\vCardDetails\x12\x1b\n" +
	"\tlast_four\x18\x01 \x01(\tR\blastFour\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x1b\n" +
	"\texp_month\x18\x03 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x04 \x01(\x05R\aexpYear\x12'\n" +
	"\x0fcardholder_name\x18\x05 \x01(\tR\x0ecardholderName\"\xc1\x01\n" +
	"\x12BankAccountDetails\x12\x1b\n" +
	"\tbank_name\x18\x01 \x01(\tR\bbankName\x12.\n" +
	"\x13account_holder_name\x18\x02 \x01(\tR\x11accountHolderName\x12*\n" +
	"\x11account_last_four\x18\x03 \x01(\tR\x0faccountLastFour\x122\n" +
	"\x15routing_number_masked\x18\x04 \x01(\tR\x13routingNumberMasked\"^\n" +
	"\x14DigitalWalletDetails\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12*\n" +
	"\x11account_id_masked\x18\x02 \x01(\tR\x0faccountIdMasked\"\xe0\x02\n" +
	"\x15ProcessPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12A\n" +
	"\x0epayment_method\x18\x05 \x01(\v2\x1a.payments.v1.PaymentMethodR\rpaymentMethod\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.payments.v1.ProcessPaymentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x16ProcessPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\x12'\n" +
	"\x0frequires_action\x18\x02 \x01(\bR\x0erequiresAction\x12\x1d\n" +
	"\n" +
	"action_url\x18\x03 \x01(\tR\tactionUrl\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x12GetPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\"J\n" +
	"\x15CapturePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\"H\n" +
	"\x16CapturePaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\"a\n" +
	"\x14RefundPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"d\n" +
	"\x15RefundPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\x12\x1b\n" +
	"\trefund_id\x18\x02 \x01(\tR\brefundId\"\xce\x01\n" +
	"\x13ListPaymentsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12?\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2\x1a.payments.v1.PaymentStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x91\x01\n" +
	"\x14ListPaymentsResponse\x120\n" +
	"\bpayments\x18\x01 \x03(\v2\x14.payments.v1.PaymentR\bpayments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x17GetPaymentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa6\x01\n" +
	"\x18GetPaymentStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.payments.v1.PaymentStatusR\x06status\x12F\n" +
	"\x11status_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fstatusUpdatedAt*\xcd\x01\n" +
	"\x11PaymentMethodType\x12#\n" +
	"\x1fPAYMENT_METHOD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PAYMENT_METHOD_TYPE_CARD\x10\x01\x12%\n" +
	"!PAYMENT_METHOD_TYPE_BANK_TRANSFER\x10\x02\x12&\n" +
	"\"PAYMENT_METHOD_TYPE_DIGITAL_WALLET\x10\x03\x12&\n" +
	"\"PAYMENT_METHOD_TYPE_CRYPTOCURRENCY\x10\x04*\xa0\x02\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_AUTHORIZED\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_CAPTURED\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SETTLED\x10\x04\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x05\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x06\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\a\x12%\n" +
	"!PAYMENT_STATUS_PARTIALLY_REFUNDED\x10\b2\xa3\x04\n" +
	"\x0ePaymentService\x12Y\n" +
	"\x0eProcessPayment\x12\".payments.v1.ProcessPaymentRequest\x1a#.payments.v1.ProcessPaymentResponse\x12M\n" +
	"\n" +
	"GetPayment\x12\x1e.payments.v1.GetPaymentRequest\x1a\x1f.payments.v1.GetPaymentResponse\x12Y\n" +
	"\x0eCapturePayment\x12\".payments.v1.CapturePaymentRequest\x1a#.payments.v1.CapturePaymentResponse\x12V\n" +
	"\rRefundPayment\x12!.payments.v1.RefundPaymentRequest\x1a\".payments.v1.RefundPaymentResponse\x12S\n" +
	"\fListPayments\x12 .payments.v1.ListPaymentsRequest\x1a!.payments.v1.ListPaymentsResponse\x12_\n" +
	"\x10GetPaymentStatus\x12$.payments.v1.GetPaymentStatusRequest\x1a%.payments.v1.GetPaymentStatusResponseB1Z/github.com/example/proto/payments/v1;paymentsv1b\x06proto3"

var (
	file_payments_v1_payment_proto_rawDescOnce sync.Once
	file_payments_v1_payment_proto_rawDescData []byte
)

func file_payments_v1_payment_proto_rawDescGZIP() []byte {
	file_payments_v1_payment_proto_rawDescOnce.Do(func() {
		file_payments_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_v1_payment_proto_rawDesc), len(file_payments_v1_payment_proto_rawDesc)))
	})
	return file_payments_v1_payment_proto_rawDescData
}

var file_payments_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payments_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_payments_v1_payment_proto_goTypes = []any{
	(PaymentMethodType)(0),           // 0: payments.v1.PaymentMethodType
	(PaymentStatus)(0),               // 1: payments.v1.PaymentStatus
	(*Payment)(nil),                  // 2: payments.v1.Payment
	(*PaymentMethod)(nil),            // 3: payments.v1.PaymentMethod
	(*CardDetails)(nil),              // 4: payments.v1.CardDetails
	(*BankAccountDetails)(nil),       // 5: payments.v1.BankAccountDetails
	(*DigitalWalletDetails)(nil),     // 6: payments.v1.DigitalWalletDetails
	(*ProcessPaymentRequest)(nil),    // 7: payments.v1.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),   // 8: payments.v1.ProcessPaymentResponse
	(*GetPaymentRequest)(nil),        // 9: payments.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),       // 10: payments.v1.GetPaymentResponse
	(*CapturePaymentRequest)(nil),    // 11: payments.v1.CapturePaymentRequest
	(*CapturePaymentResponse)(nil),   // 12: payments.v1.CapturePaymentResponse
	(*RefundPaymentRequest)(nil),     // 13: payments.v1.RefundPaymentRequest
	(*RefundPaymentResponse)(nil),    // 14: payments.v1.RefundPaymentResponse
	(*ListPaymentsRequest)(nil),      // 15: payments.v1.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),     // 16: payments.v1.ListPaymentsResponse
	(*GetPaymentStatusRequest)(nil),  // 17: payments.v1.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil), // 18: payments.v1.GetPaymentStatusResponse
	nil,                              // 19: payments.v1.Payment.MetadataEntry
	nil,                              // 20: payments.v1.ProcessPaymentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_payments_v1_payment_proto_depIdxs = []int32{
	3,  // 0: payments.v1.Payment.method:type_name -> payments.v1.PaymentMethod
	1,  // 1: payments.v1.Payment.status:type_name -> payments.v1.PaymentStatus
	21, // 2: payments.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	21, // 3: payments.v1.Payment.processed_at:type_name -> google.protobuf.Timestamp
	19, // 4: payments.v1.Payment.metadata:type_name -> payments.v1.Payment.MetadataEntry
	0,  // 5: payments.v1.PaymentMethod.type:type_name -> payments.v1.PaymentMethodType
	4,  // 6: payments.v1.PaymentMethod.card:type_name -> payments.v1.CardDetails
	5,  // 7: payments.v1.PaymentMethod.bank_account:type_name -> payments.v1.BankAccountDetails
	6,  // 8: payments.v1.PaymentMethod.digital_wallet:type_name -> payments.v1.DigitalWalletDetails
	3,  // 9: payments.v1.ProcessPaymentRequest.payment_method:type_name -> payments.v1.PaymentMethod
	20, // 10: payments.v1.ProcessPaymentRequest.metadata:type_name -> payments.v1.ProcessPaymentRequest.MetadataEntry
	2,  // 11: payments.v1.ProcessPaymentResponse.payment:type_name -> payments.v1.Payment
	2,  // 12: payments.v1.GetPaymentResponse.payment:type_name -> payments.v1.Payment
	2,  // 13: payments.v1.CapturePaymentResponse.payment:type_name -> payments.v1.Payment
	2,  // 14: payments.v1.RefundPaymentResponse.payment:type_name -> payments.v1.Payment
	1,  // 15: payments.v1.ListPaymentsRequest.status_filter:type_name -> payments.v1.PaymentStatus
	2,  // 16: payments.v1.ListPaymentsResponse.payments:type_name -> payments.v1.Payment
	1,  // 17: payments.v1.GetPaymentStatusResponse.status:type_name -> payments.v1.PaymentStatus
	21, // 18: payments.v1.GetPaymentStatusResponse.status_updated_at:type_name -> google.protobuf.Timestamp
	7,  // 19: payments.v1.PaymentService.ProcessPayment:input_type -> payments.v1.ProcessPaymentRequest
	9,  // 20: payments.v1.PaymentService.GetPayment:input_type -> payments.v1.GetPaymentRequest
	11, // 21: payments.v1.PaymentService.CapturePayment:input_type -> payments.v1.CapturePaymentRequest
	13, // 22: payments.v1.PaymentService.RefundPayment:input_type -> payments.v1.RefundPaymentRequest
	15, // 23: payments.v1.PaymentService.ListPayments:input_type -> payments.v1.ListPaymentsRequest
	17, // 24: payments.v1.PaymentService.GetPaymentStatus:input_type -> payments.v1.GetPaymentStatusRequest
	8,  // 25: payments.v1.PaymentService.ProcessPayment:output_type -> payments.v1.ProcessPaymentResponse
	10, // 26: payments.v1.PaymentService.GetPayment:output_type -> payments.v1.GetPaymentResponse
	12, // 27: payments.v1.PaymentService.CapturePayment:output_type -> payments.v1.CapturePaymentResponse
	14, // 28: payments.v1.PaymentService.RefundPayment:output_type -> payments.v1.RefundPaymentResponse
	16, // 29: payments.v1.PaymentService.ListPayments:output_type -> payments.v1.ListPaymentsResponse
	18, // 30: payments.v1.PaymentService.GetPaymentStatus:output_type -> payments.v1.GetPaymentStatusResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_payments_v1_payment_proto_init() }
func file_payments_v1_payment_proto_init() {
	if File_payments_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_v1_payment_proto_rawDesc), len(file_payments_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_v1_payment_proto_goTypes,
		DependencyIndexes: file_payments_v1_payment_proto_depIdxs,
		EnumInfos:         file_payments_v1_payment_proto_enumTypes,
		MessageInfos:      file_payments_v1_payment_proto_msgTypes,
	}.Build()
	File_payments_v1_payment_proto = out.File
	file_payments_v1_payment_proto_goTypes = nil
	file_payments_v1_payment_proto_depIdxs = nil
}
