import 'dart:io';
import 'dart:typed_data';

// Generated protobuf imports (will be generated by bufrnix)
// import 'proto/gen/dart/example/v1/example.pb.dart';
// import 'proto/gen/dart/example/v1/example.pbgrpc.dart';

void main() {
  print('Dart Protobuf Example');
  print('=====================');
  
  // This will be uncommented once protobuf code is generated
  /*
  try {
    // Demonstrate creating and using protobuf messages
    demoProtobufMessages();
    
    // Demonstrate serialization/deserialization
    demoSerialization();
    
    print('\nExample completed successfully!');
  } catch (e) {
    print('Error: $e');
    exit(1);
  }
  */
  
  print('Run "nix build" to generate protobuf code first.');
}

// Uncomment these functions after protobuf generation
/*
void demoProtobufMessages() {
  print('\n--- Protobuf Message Demo ---');
  
  // Create a timestamp
  final timestamp = TimestampMessage()
    ..seconds = DateTime.now().millisecondsSinceEpoch ~/ 1000
    ..nanos = 0;
    
  // Create an example message
  final example = ExampleMessage()
    ..id = 1
    ..name = 'John Doe'
    ..email = 'john.doe@example.com'
    ..tags.addAll(['developer', 'dart', 'protobuf'])
    ..description = 'A sample user for testing protobuf generation'
    ..createdAt = timestamp;
    
  print('Created example: ${example.toString()}');
  
  // Create request/response messages
  final createRequest = CreateExampleRequest()
    ..example = example;
    
  print('Create request: ${createRequest.toString()}');
  
  final listRequest = ListExamplesRequest()
    ..pageSize = 10
    ..pageToken = ''
    ..filter = 'active:true';
    
  print('List request: ${listRequest.toString()}');
}

void demoSerialization() {
  print('\n--- Serialization Demo ---');
  
  // Create an example message
  final original = ExampleMessage()
    ..id = 42
    ..name = 'Test User'
    ..email = 'test@example.com'
    ..tags.addAll(['test', 'serialization']);
    
  // Serialize to bytes
  final bytes = original.writeToBuffer();
  print('Serialized to ${bytes.length} bytes');
  
  // Deserialize from bytes
  final deserialized = ExampleMessage.fromBuffer(bytes);
  print('Deserialized: ${deserialized.toString()}');
  
  // Verify they're equal
  if (original.id == deserialized.id && 
      original.name == deserialized.name &&
      original.email == deserialized.email) {
    print('✓ Serialization/deserialization successful!');
  } else {
    print('✗ Serialization/deserialization failed!');
  }
}
*/