#!/bin/sh
# Wrapper script to ensure mbstring is loaded
PHP_INI_SCAN_DIR=/home/connerohnesorge/Documents/001Repos/bufrnix/examples/php-twirp/.nix-php /nix/store/inbybpkivlgsgnhl2hldgyz16sqhzdi2-php-with-extensions-8.3.21/bin/php -n -c /home/connerohnesorge/Documents/001Repos/bufrnix/examples/php-twirp/.nix-php/php.ini "$@"
